---
- name: Demo play (rescue)
  hosts: localhost
  tasks:

  - block:
    - name: Run this script, if it fails then rescue runs
      shell: id

    rescue:
    - name: this will only run if the previos task failed
      shell: echo I have run

    always:
    - name: This will always run
      shell: echo Done


