---
- name: Demo play (loop and register vars)
  hosts: localhost
  gather_facts: no
  tasks:

  - name: Do something random
    shell: "echo this is {{ item }}"
    loop:
      - Jacques
      - Bob
      - Sarah
    register: output

  - name: Debug the var output-results
    debug:
      var: output['results']['item']

